"""Independent Media Foundation contracts transcribed from Microsoft's header.

Source: microsoft/win32metadata, generation/WinSDK/RecompiledIdlHeaders/um/
mfmediaengine.h, inspected 2026-09-14 (not values generated by ctypes_layout).
Edge cases: missing tail slots, alphabetical reordering, and scalar/pointer
confusion must fail independently of the C++ reference emitter. Raw callbacks
below test dispatch only; they do not emulate or qualify Windows Media Foundation.
"""
from __future__ import annotations

import ctypes as ct
from pathlib import Path

import pytest

from src.video.component_base import definitions_abi as abi

UNKNOWN = ("QueryInterface", "AddRef", "Release")
SDK_SLOTS = {
    "IMFTimedTextTrackVtbl": UNKNOWN + (
        "GetId", "GetLabel", "SetLabel", "GetLanguage", "GetTrackKind", "IsInBand",
        "GetInBandMetadataTrackDispatchType", "IsActive", "GetErrorCode",
        "GetExtendedErrorCode", "GetDataFormat", "GetReadyState", "GetCueList",
    ),
    "IMFTimedTextVtbl": UNKNOWN + (
        "RegisterNotifications", "SelectTrack", "AddDataSource", "AddDataSourceFromUrl",
        "AddTrack", "RemoveTrack", "GetCueTimeOffset", "SetCueTimeOffset", "GetTracks",
        "GetActiveTracks", "GetTextTracks", "GetMetadataTracks", "SetInBandEnabled",
        "IsInBandEnabled",
    ),
    "IMFMediaEngineClassFactoryVtbl": UNKNOWN + (
        "CreateInstance", "CreateTimeRange", "CreateError",
    ),
}
P = ct.POINTER
THIS = ct.c_void_p
HR = ct.c_long  # Windows HRESULT is LONG; do not derive this oracle from abi.HRESULT.
DWORD = ct.wintypes.DWORD
BOOL = ct.wintypes.BOOL
WSTR = ct.wintypes.LPWSTR
CWSTR = ct.wintypes.LPCWSTR
CALL = getattr(ct, "WINFUNCTYPE", ct.CFUNCTYPE)


def sdk_signatures() -> dict[str, dict[str, tuple[object, ...]]]:
    """Return independently specified return/argument types, including This."""
    track = P(abi.IMFTimedTextTrack)
    track_list = P(P(abi.IMFTimedTextTrackList))
    signatures = {
        "IMFTimedTextTrackVtbl": {
            "GetId": (DWORD, THIS), "GetLabel": (HR, THIS, P(WSTR)),
            "SetLabel": (HR, THIS, CWSTR), "GetLanguage": (HR, THIS, P(WSTR)),
            "GetTrackKind": (ct.c_uint32, THIS),
            "IsInBand": (BOOL, THIS),
            "GetInBandMetadataTrackDispatchType": (HR, THIS, P(WSTR)),
            "IsActive": (BOOL, THIS), "GetErrorCode": (ct.c_uint32, THIS),
            "GetExtendedErrorCode": (HR, THIS), "GetDataFormat": (HR, THIS, P(abi.GUID)),
            "GetReadyState": (ct.c_uint32, THIS),
            "GetCueList": (HR, THIS, P(P(abi.IMFTimedTextCueList))),
        },
        "IMFTimedTextVtbl": {
            "RegisterNotifications": (HR, THIS, P(abi.IMFTimedTextNotify)),
            "SelectTrack": (HR, THIS, DWORD, BOOL),
            "AddDataSource": (HR, THIS, P(abi.IMFByteStream), CWSTR, CWSTR,
                              ct.c_uint32, BOOL, P(DWORD)),
            "AddDataSourceFromUrl": (HR, THIS, CWSTR, CWSTR, CWSTR,
                                     ct.c_uint32, BOOL, P(DWORD)),
            "AddTrack": (HR, THIS, CWSTR, CWSTR, ct.c_uint32, P(track)),
            "RemoveTrack": (HR, THIS, track),
            "GetCueTimeOffset": (HR, THIS, P(ct.c_double)),
            "SetCueTimeOffset": (HR, THIS, ct.c_double),
            "GetTracks": (HR, THIS, track_list), "GetActiveTracks": (HR, THIS, track_list),
            "GetTextTracks": (HR, THIS, track_list), "GetMetadataTracks": (HR, THIS, track_list),
            "SetInBandEnabled": (HR, THIS, BOOL), "IsInBandEnabled": (BOOL, THIS),
        },
        "IMFMediaEngineClassFactoryVtbl": {
            "CreateInstance": (HR, THIS, ct.c_uint32, P(abi.IMFAttributes), P(P(abi.IMFMediaEngine))),
            "CreateTimeRange": (HR, THIS, P(P(abi.IMFMediaTimeRange))),
            "CreateError": (HR, THIS, P(P(abi.IMFMediaError))),
        },
    }
    for methods in signatures.values():
        methods.update(QueryInterface=(HR, THIS, P(abi.GUID), P(THIS)),
                       AddRef=(ct.c_ulong, THIS), Release=(ct.c_ulong, THIS))
    return signatures


@pytest.mark.parametrize("name,names", SDK_SLOTS.items())
def test_all_slots_match_header_order_size_and_offsets(name: str, names: tuple[str, ...]) -> None:
    kind = getattr(abi, name)
    assert tuple(field[0] for field in kind._fields_) == names
    width = ct.sizeof(THIS)
    assert ct.sizeof(kind) == len(names) * width
    assert ct.alignment(kind) == ct.alignment(THIS)
    assert {field: getattr(kind, field).offset for field in names} == {
        field: index * width for index, field in enumerate(names)
    }


@pytest.mark.parametrize("name", SDK_SLOTS)
def test_all_scoped_method_signatures_match_header(name: str) -> None:
    actual = dict(getattr(abi, name)._fields_)
    expected = sdk_signatures()[name]
    assert set(actual) == set(expected)
    for method, signature in expected.items():
        assert actual[method]._restype_ is signature[0], method
        assert actual[method]._argtypes_ == signature[1:], method


def _raw_interface(kind: type[ct.Structure], slots: int, index: int, callback: ct._CFuncPtr) -> tuple[object, tuple[object, ...]]:
    """Build only a test-owned pointer table at an independently selected slot."""
    table = (THIS * slots)()
    table[index] = ct.cast(callback, THIS).value
    address = ct.cast(table, THIS)
    return ct.cast(ct.pointer(address), P(kind)), (table, address, callback)


def test_get_id_dispatches_sdk_slot_3_not_alphabetical_slot_6() -> None:
    callback = CALL(DWORD, THIS)(lambda this: 0xF000001D)
    pointer, keepalive = _raw_interface(abi.IMFTimedTextTrack, 16, 3, callback)
    # Prevent unsafe access on a broken baseline: check the index before calling.
    assert abi.IMFTimedTextTrackVtbl.GetId.offset == 3 * ct.sizeof(THIS)
    assert pointer.contents.lpVtbl.contents.GetId(pointer) == 0xF000001D
    assert keepalive


def test_select_track_dispatches_sdk_slot_4_with_id_and_bool() -> None:
    calls = []

    def selected(this: int, track_id: int, enabled: int) -> int:
        calls.append((track_id, enabled))
        return 0

    callback = CALL(HR, THIS, DWORD, BOOL)(selected)
    pointer, keepalive = _raw_interface(abi.IMFTimedText, 17, 4, callback)
    assert abi.IMFTimedTextVtbl.SelectTrack.offset == 4 * ct.sizeof(THIS)
    assert pointer.contents.lpVtbl.contents.SelectTrack(pointer, 37, 1) == 0
    assert calls == [(37, 1)]
    assert keepalive


def test_remove_track_preserves_pointer_and_rejects_integer_id() -> None:
    calls = []

    def removed(this: int, track: object) -> int:
        calls.append(ct.cast(track, THIS).value)
        return 0

    callback = CALL(HR, THIS, P(abi.IMFTimedTextTrack))(removed)
    pointer, keepalive = _raw_interface(abi.IMFTimedText, 17, 8, callback)
    track = abi.IMFTimedTextTrack()
    assert abi.IMFTimedTextVtbl.RemoveTrack.offset == 8 * ct.sizeof(THIS)
    method = pointer.contents.lpVtbl.contents.RemoveTrack
    assert method(pointer, ct.pointer(track)) == 0
    assert calls == [ct.addressof(track)]
    with pytest.raises((ct.ArgumentError, TypeError)):
        method(pointer, 37)
    assert calls == [ct.addressof(track)]
    assert keepalive


def test_compiled_reference_emits_every_scoped_slot_once() -> None:
    source = (Path(__file__).resolve().parents[1] / "tools/abi_harness/reference_layout.cpp").read_text(encoding="utf-8")
    for table, names in SDK_SLOTS.items():
        block = source.split(f"BEGIN_TYPE({table});", 1)[1].split("END_TYPE(", 1)[0]
        import re
        emitted = re.findall(r"(?:LAST_)?FIELD\(\w+, (\w+)\)", block)
        assert tuple(emitted) == names, table
        for name in names:
            assert f"CHECK_METHOD({table}, {name}," in source
