# -*- coding: utf-8 -*-
"""Media Foundation MediaEngine event identifiers.

The constants are kept in a dedicated module because they form a stable,
standalone vocabulary consumed by multiple adapter/event layers.
"""

from __future__ import annotations

MF_MEDIA_ENGINE_EVENT_LOADSTART = 1
MF_MEDIA_ENGINE_EVENT_PROGRESS = 2
MF_MEDIA_ENGINE_EVENT_SUSPEND = 3
MF_MEDIA_ENGINE_EVENT_ABORT = 4
MF_MEDIA_ENGINE_EVENT_ERROR = 5
MF_MEDIA_ENGINE_EVENT_EMPTIED = 6
MF_MEDIA_ENGINE_EVENT_STALLED = 7
MF_MEDIA_ENGINE_EVENT_PLAY = 8
MF_MEDIA_ENGINE_EVENT_PAUSE = 9
MF_MEDIA_ENGINE_EVENT_LOADEDMETADATA = 10
MF_MEDIA_ENGINE_EVENT_LOADEDDATA = 11
MF_MEDIA_ENGINE_EVENT_WAITING = 12
MF_MEDIA_ENGINE_EVENT_PLAYING = 13
MF_MEDIA_ENGINE_EVENT_CANPLAY = 14
MF_MEDIA_ENGINE_EVENT_CANPLAYTHROUGH = 15
MF_MEDIA_ENGINE_EVENT_SEEKING = 16
MF_MEDIA_ENGINE_EVENT_SEEKED = 17
MF_MEDIA_ENGINE_EVENT_TIMEUPDATE = 18
MF_MEDIA_ENGINE_EVENT_ENDED = 19
MF_MEDIA_ENGINE_EVENT_RATECHANGE = 20
MF_MEDIA_ENGINE_EVENT_DURATIONCHANGE = 21
MF_MEDIA_ENGINE_EVENT_VOLUMECHANGE = 22

MF_MEDIA_ENGINE_EVENT_FORMATCHANGE = 1000
MF_MEDIA_ENGINE_EVENT_PURGEQUEUEDEVENTS = 1001
