# Moved from src.ui.visualizer_view to neutral audio layer.
# NOTE: This file is generated by refactor to avoid upward UI dependency.
from __future__ import annotations

import logging
import math
import threading
import wave
from typing import Optional, Tuple

import numpy as np

try:
    import soundfile as sf  # Optional for broad codec support
except (ImportError, OSError, RuntimeError):  # pragma: no cover
    sf = None

logger = logging.getLogger(__name__)

ANALYZER_LOAD_EXCEPTIONS = (AttributeError, OSError, RuntimeError, TypeError, ValueError)
ANALYZER_WAV_EXCEPTIONS = (EOFError, OSError, TypeError, ValueError, wave.Error)


class AudioAnalyzer:
    def __init__(
        self, fft_size: int = 4096, sample_rate: int = 44100, num_bands: int = 32
    ):
        self._lock = threading.RLock()
        self.fft_size = int(fft_size)
        self.sample_rate = int(sample_rate)
        self.num_bands = 32 if int(num_bands) <= 32 else 64
        self.window = np.hanning(self.fft_size).astype(np.float32)
        self.freqs = np.fft.rfftfreq(self.fft_size, 1.0 / self.sample_rate)
        self.band_edges, self.band_centers = self._make_log_bands(self.num_bands)
        self._precompute_ranges()

    def _reduce_band_segment(self, seg: np.ndarray) -> float:
        if seg.size == 0:
            return -90.0
        mean_db = float(np.mean(seg))
        peak_db = float(np.max(seg))
        return mean_db + 0.25 * (peak_db - mean_db)

    def set_num_bands(self, n: int):
        with self._lock:
            n = 32 if int(n) <= 32 else 64
            if n == self.num_bands:
                return
            self.num_bands = n
            self.band_edges, self.band_centers = self._make_log_bands(n)
            self._precompute_ranges()

    def _make_log_bands(
        self, n_bands: int, f_min: float = 20.0, f_max: float = 20000.0
    ):
        nyq = self.sample_rate / 2.0
        f_max = min(f_max, nyq)
        centers = np.logspace(np.log10(f_min), np.log10(f_max), num=n_bands).astype(
            np.float32
        )
        edges = np.empty(n_bands + 1, dtype=np.float32)
        edges[0] = max(20.0, float(centers[0]) / math.sqrt(2.0))
        for i in range(n_bands - 1):
            edges[i + 1] = math.sqrt(float(centers[i]) * float(centers[i + 1]))
        edges[-1] = min(nyq, float(centers[-1]) * math.sqrt(2.0))
        return edges, centers

    def _precompute_ranges(self):
        ranges = np.zeros((self.num_bands, 2), dtype=np.int32)
        for i in range(self.num_bands):
            lo = float(self.band_edges[i])
            hi = float(self.band_edges[i + 1])
            lo_idx = int(np.searchsorted(self.freqs, lo, side="left"))
            hi_idx = int(np.searchsorted(self.freqs, hi, side="left"))
            if hi_idx <= lo_idx:
                hi_idx = min(lo_idx + 1, len(self.freqs))
            lo_idx = max(0, min(lo_idx, len(self.freqs) - 1))
            hi_idx = max(lo_idx + 1, min(hi_idx, len(self.freqs)))
            ranges[i, 0] = lo_idx
            ranges[i, 1] = hi_idx
        self._ranges = ranges

    def load_audio_file(self, path: str) -> Optional[np.ndarray]:
        try:
            audio = None
            sr = None
            try:
                import soundfile as sf

                audio, sr = sf.read(path, dtype="float32")
            except ANALYZER_LOAD_EXCEPTIONS:
                audio, sr = self._load_wav_basic(path)
            if audio is None or sr is None:
                return None
            if audio.ndim == 2:
                audio = audio.mean(axis=1)
            if int(sr) != self.sample_rate:
                audio = self._resample_linear(audio, int(sr), self.sample_rate)
            return audio.astype(np.float32, copy=False)
        except ANALYZER_LOAD_EXCEPTIONS as error:
            logger.error(f"[Analyzer] load_audio_file failed: {error}")
            return None

    def _load_wav_basic(self, path: str):
        try:
            if not str(path).lower().endswith(".wav"):
                return None, None
            with wave.open(path, "rb") as w:
                n_frames = w.getnframes()
                sr = w.getframerate()
                n_ch = w.getnchannels()
                sw = w.getsampwidth()
                raw = w.readframes(n_frames)
            if sw == 1:
                data = np.frombuffer(raw, dtype=np.uint8).astype(np.float32)
                data = (data - 128.0) / 128.0
            elif sw == 2:
                data = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
            elif sw == 4:
                data = (
                    np.frombuffer(raw, dtype=np.int32).astype(np.float32) / 2147483648.0
                )
            else:
                return None, None
            if n_ch == 2:
                data = data.reshape(-1, 2).mean(axis=1)
            return data, sr
        except ANALYZER_WAV_EXCEPTIONS:
            return None, None

    def _resample_linear(self, x: np.ndarray, sr_in: int, sr_out: int) -> np.ndarray:
        if sr_in == sr_out or x.size == 0:
            return x
        ratio = float(sr_out) / float(sr_in)
        n_new = max(1, int(round(x.size * ratio)))
        idx = np.linspace(0, x.size - 1, n_new, dtype=np.float32)
        return np.interp(idx, np.arange(x.size, dtype=np.float32), x).astype(np.float32)

    def analyze_at(
        self, audio_data: np.ndarray, pos_samples: int
    ) -> Tuple[np.ndarray, np.ndarray]:
        with self._lock:
            start = max(0, int(pos_samples) - self.fft_size // 2)
            windowed = np.zeros(self.fft_size, dtype=np.float32)
            available = max(0, min(audio_data.size - start, self.fft_size))
            if available > 0:
                windowed[:available] = audio_data[start : start + available]
            windowed *= self.window
            spec = np.abs(np.fft.rfft(windowed))
            with np.errstate(divide="ignore"):
                db = 20.0 * np.log10(spec + 1e-12)
            band_vals = np.empty(self.num_bands, dtype=np.float32)
            for i in range(self.num_bands):
                lo, hi = self._ranges[i]
                seg = db[lo:hi]
                band_vals[i] = self._reduce_band_segment(seg)
            p20 = float(np.percentile(band_vals, 20))
            p95 = float(np.percentile(band_vals, 95))
            rng = max(1e-6, p95 - p20)
            norm = np.clip((band_vals - p20) / rng, 0.0, 1.0)
            norm = (norm**1.35) * 0.95
            norm = np.clip(norm, 0.0, 0.95)
            return self.band_centers.copy(), norm

    def analyze(self, audio_chunk: "np.ndarray") -> "np.ndarray":
        import numpy as np

        with self._lock:
            x = np.asarray(audio_chunk, dtype=np.float32)
            if x.ndim == 2:
                x = x.mean(axis=1)

            if x.size < self.fft_size:
                x = np.pad(x, (0, self.fft_size - x.size), mode="constant")
            elif x.size > self.fft_size:
                x = x[: self.fft_size]

            x = x * self.window
            spec = np.abs(np.fft.rfft(x))
            with np.errstate(divide="ignore"):
                db = 20.0 * np.log10(spec / (np.max(spec) + 1e-12) + 1e-12)

            band_vals = np.zeros(self.num_bands, dtype=np.float32)
            for i in range(self.num_bands):
                lo, hi = self._ranges[i]
                seg = db[lo:hi]
                band_vals[i] = self._reduce_band_segment(seg)

            p20 = float(np.percentile(band_vals, 20))
            p95 = float(np.percentile(band_vals, 95))
            rng = max(1e-6, p95 - p20)
            norm = np.clip((band_vals - p20) / rng, 0.0, 1.0)
            norm = (norm**1.35) * 0.95
            return np.clip(norm, 0.0, 0.95)
